### ISSUE TITLE
Failing to generate image previews for shots

### ISSUE THREAD

**Issue by fsiddi** [armadillica/pillar-web#6]
This is the Traceback:
```
Traceback (most recent call last):
  File "/shared/software/attract3/venv-web/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/shared/software/attract3/venv-web/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/shared/software/attract3/venv-web/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/shared/software/attract3/venv-web/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/shared/software/attract3/venv-web/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/shared/software/attract3/venv-web/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/shared/software/attract3/venv-web/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/shared/software/attract3/venv-web/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/shared/software/attract3/venv-web/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/shared/software/attract3/attract-web/attract-web/attract/application/modules/files/__init__.py", line 86, in index
    node_picture.build_previews(name, api=api)
TypeError: 'NoneType' object is not callable
````

**Comment by fsiddi** [comment]
The codebase has changed and the issue is not valid anymore.
